### ISSUE TITLE
Won't build images

### ISSUE THREAD

**Issue by ManikClub** [sazzadul4201/nfts-generator#1]
X:\nfts-generator-main>npm run build

> hashlips_art_engine@1.1.1 build
> node index.js

(node:4172) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1390
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'X:\nfts-generator-main/layers/1cap/'
    at Object.readdirSync (node:fs:1390:3)
    at getElements (X:\nfts-generator-main\src\main.js:76:6)
    at X:\nfts-generator-main\src\main.js:92:15
    at Array.map (<anonymous>)
    at layersSetup (X:\nfts-generator-main\src\main.js:90:30)
    at startCreating (X:\nfts-generator-main\src\main.js:363:20)
    at X:\nfts-generator-main\index.js:6:3
    at Object.<anonymous> (X:\nfts-generator-main\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'X:\\nfts-generator-main/layers/1cap/'

**Comment by md-sazzadul-islam** [comment]
no such file or directory, scandir 'X:\nfts-generator-main/layers/1cap/'
need to set your layer in layers folder and src/config.jg -> layerConfigurations 

Thank you.
